### ISSUE TITLE
Bug in class GraphicState

### ISSUE THREAD

**Issue by karstenw** [typemytype/drawbot#19]
In GraphicsState.setColorSpace() the call to self.updateColorSpace should have some dummy argument.

https://github.com/typemytype/drawbot/blob/master/drawBot/context/baseContext.py#L1010

This breaks the colorspace.py example

P.S.: Is there any specific reason for the OSX 10.9 requirement?

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/drawbot/commit/89a099ed60ebf745d265333e1872d9c373444ffe

I guess it should be possible to compile the app for older OS's but it seems not be possible to have a single compiled app made with py2app both for a wider range of OS versions. And ... I don't want to provide support for older OS's. 

Hope this makes sense. If you can make a robust setup.py, that is able to generate a working compiled app for a wider range of OS versions, please send a pull request.

thanks

**Comment by karstenw** [comment]
>If you can make a robust setup.py, that is able to generate a working compiled app for a wider range of OS versions

AFAIK the building OS determines the executability on newer OSes. I have a 10.6 fork which runs nicely on 10.6.8 and 10.10.4; the OSes I have in use. I just made sure that it also builds on 10.10.

To my surprise, the 10.10 build app also runs on 10.6... 

It's 32-bit only if build on 10.6 and 64-bit only otherwise and runs all the provided examples.

Making a pull request...
