### ISSUE TITLE
embed installed fonts in a svg context

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#23]
use:

``` xml
<defs>
  <style type="text/css">
    @font-face {
      font-family: Delicious;
      src: url('../fonts/font.woff');
      src: url("data:application/font-woff;charset=utf-8;base64,...");
    }
  </style>
</defs>
```

use url when it is an url or base64 when it is a local file

**Comment by justvanrossum** [comment]
Oh my, and then we probably should do subsetting, too? :)

**Comment by typemytype** [comment]
fontTools has a subsetter...
or maybe not...

**Comment by justvanrossum** [comment]
Indeed it does, but it will require us to analyze the content.

**Comment by typemytype** [comment]
without subsetting...
but maybe subsetting is the users responsibility?

https://github.com/typemytype/drawbot/commit/22f004f1081dca38139fa494e2fd35003b0394cd

**Comment by justvanrossum** [comment]
Nice, but raises the question: shouldn't fonts then *always* be embedded, like presumable Apple's PDF generator does. Right now, fonts that are installed "normally" (~/Library/Fonts or whatever) are not embedded.

I'm not a fan of non-subsetted embedding, so I prefer no embedding as long as we can't do subsetting. The risk of accidental font distribution is just too big, *especially* since the temp font install feature is useful to create proofs for works in progress...

**Comment by justvanrossum** [comment]
Is this already part of DrawBot 3.69? It's really not a good thing I'm afraid.

**Comment by typemytype** [comment]
the current status is: svg has no embedded fonts and relies on user install fonts or provided web fonts when displayed in a html page

lets keep it like this
